[package]
name = "mock-client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mock-client"
path = "src/main.rs"

[dependencies]
futures = "0"
tokio = {workspace = true}
tokio-util  ={ version = "0", features = ["codec"] }
thiserror = { workspace = true }
